### PR TITLE
fix: delete stale or invalid resume token for mongo client changeStreams

### LINKED ISSUE #955: [Bug]: fault-remediation module is stuck with error :"Failed to watch change stream" after v0.7.1 upgrade
### Prerequisites

- [x] I searched existing issues
- [x] I can reproduce this issue

### Bug Description

when fault-remediation comes up, it is not able to watch the mongodb changestream and is throwing the below error

```
{"time":"2026-02-26T11:55:55.346439016Z","level":"ERROR","msg":"Failed to watch change stream","module":"fault-remediation","version":"v0.7.1","client":"watcher-factory","error":"(ChangeStreamFatalError) Executor error during getMore :: caused by :: cannot resume stream; the resume token was not found. {_data: \"8269A0042C000000732B042C0100296E5A1004A6C9E0BC444A494DA06DA649B45E45E3463C6F7065726174696F6E54797065003C7570646174650046646F63756D656E744B65790046645F6964006469A0042CE2A00114E4C9D718000004\"}"}
```

it needs to be checked how best to remediate it. 

### Component

Health Monitor

### Steps to Reproduce

 After upgrade to v0.7.1, this issue is coming. This is seen only once and there is no mechanism to repro this yet.

### Environment

- NVSentinel version: V0.7.1
- Kubernetes version:v1.29.15
- Deployment method: helm chart

### Logs/Output

```
{"time":"2026-02-26T11:55:55.346433518Z","level":"ERROR","msg":"Failed to watch change stream","module":"fault-remediation","version":"v0.7.1","client":"watcher-factory","error":"(ChangeStreamFatalError) Executor error during getMore :: caused by :: cannot resume stream; the resume token was not found. {_data: \"8269A0042C000000732B042C0100296E5A1004A6C9E0BC444A494DA06DA649B45E45E3463C6F7065726174696F6E54797065003C7570646174650046646F63756D656E744B65790046645F6964006469A0042CE2A00114E4C9D718000004\"}"}
{"time":"2026-02-26T11:55:55.346435161Z","level":"ERROR","msg":"Failed to watch change stream","module":"fault-remediation","version":"v0.7.1","client":"watcher-factory","error":"(ChangeStreamFatalError) Executor error during getMore :: caused by :: cannot resume stream; the resume token was not found. {_data: \"8269A0042C000000732B042C0100296E5A1004A6C9E0BC444A494DA06DA649B45E45E3463C6F7065726174696F6E54797065003C7570646174650046646F63756D656E744B65790046645F6964006469A0042CE2A00114E4C9D718000004\"}"}
{"time":"2026-02-26T11:55:55.346437384Z","level":"ERROR","msg":"Failed to watch change stream","module":"fault-remediation","version":"v0.7.1","client":"watcher-factory","error":"(ChangeStreamFatalError) Executor error during getMore :: caused by :: cannot resume stream; the resume token was not found. {_data: \"8269A0042C000000732B042C0100296E5A1004A6C9E0BC444A494DA06DA649B45E45E3463C6F7065726174696F6E54797065003C7570646174650046646F63756D656E744B65790046645F6964006469A0042CE2A00114E4C9D718000004\"}"}
{"time":"2026-02-26T11:55:55.346439016Z","level":"ERROR","msg":"Failed to watch change stream","module":"fault-remediation","version":"v0.7.1","client":"watcher-factory","error":"(ChangeStreamFatalError) Executor error during getMore :: caused by :: cannot resume stream; the resume token was not found. {_data: \"8269A0042C000000732B042C0100296E5A1004A6C9E0BC444A494DA06DA649B45E45E3463C6F7065726174696F6E54797065003C7570646174650046646F63756D656E744B65790046645F6964006469A0042CE2A00114E4C9D718000004\"}"}
{"time":"2026-02-26T11:55:55.346440729Z","level":"ERROR","msg":"Failed to watch change stream","module":"fault-remediation","version":"v0.7.1","client":"watcher-factory","error":"(ChangeStreamFatalError) Executor error during getMore :: caused by :: cannot resume stream; the resume token was not found. {_data: \"8269A0042C000000732B042C0100296E5A1004A6C9E0BC444A494DA06DA649B45E45E3463C6F7065726174696F6E54797065003C7570646174650046646F63756D656E744B65790046645F6964006469A0042CE2A00114E4C9D718000004\"}"}
{"time":"2026-02-26T11:55:55.346442412Z","level":"ERROR","msg":"Failed to watch change stream","module":"fault-remediation","version":"v0.7.1","client":"watcher-factory","error":"(ChangeStreamFatalError) Executor error during getMore :: caused by :: cannot resume stream; the resume token was not found. {_data: \"8269A0042C000000732B042C0100296E5A1004A6C9E0BC444A494DA06DA649B45E45E3463C6F7065726174696F6E54797065003C7570646174650046646F63756D656E744B65790046645F6964006469A0042CE2A00114E4C9D718000004\"}"}
{"time":"2026-02-26T11:55:55.346444104Z","level":"ERROR","msg":"Failed to watch change stream","module":"fault-remediation","version":"v0.7.1","client":"watcher-factory","error":"(ChangeStreamFatalError) Executor error during getMore :: caused by :: cannot resume stream; the resume token was not found. {_data: \"8269A0042C000000732B042C0100296E5A1004A6C9E0BC444A494DA06DA649B45E45E3463C6F7065726174696F6E54797065003C7570646174650046646F63756D656E744B65790046645F6964006469A0042CE2A00114E4C9D718000004\"}"}
{"time":"2026-02-26T11:55:55.346445787Z","level":"ERROR","msg":"Failed to watch change stream","module":"fault-remediation","version":"v0.7.1","client":"watcher-factory","error":"(ChangeStreamFatalError) Executor error during getMore :: caused by :: cannot resume stream; the resume token was not found. {_data: \"8269A0042C000000732B042C0100296E5A1004A6C9E0BC444A494DA06DA649B45E45E3463C6F7065726174696F6E54797065003C7570646174650046646F63756D656E744B65790046645F6964006469A0042CE2A00114E4C9D718000004\"}"}
{"time":"2026-02-26T11:55:55.346447439Z","level":"ERROR","msg":"Failed to watch change stream","module":"fault-remediation","version":"v0.7.1","client":"watcher-factory","error":"(ChangeStreamFatalError) Executor error during getMore :: caused by :: cannot resume stream; the resume token was not found. {_data: \"8269A0042C000000732B042C0100296E5A1004A6C9E0BC444A494DA06DA649B45E45E3463C6F7065726174696F6E54797065003C7570646174650046646F63756D656E744B65790046645F6964006469A0042CE2A00114E4C9D718000004\"}"}
```

### PR DESCRIPTION
**Pull request by KaivalyaMDabhadkar**
## Summary

Fixes fault-remediation and node-drainer entering an unrecoverable `CrashLoopBackOff` after upgrades on quiet clusters.

Two independent defects combine into a fatal cycle: a stale MongoDB resume token blocks initialization, and the liveness probe architecture kills the pod before it can ever recover, restarting it into the exact same failure state.

### Root Cause 1: Stale Resume Token With No Recovery Mechanism

The `ChangeStreamWatcher` stores a resume token in the `ResumeTokens` MongoDB collection after processing each event. On restart, it loads this token and calls `SetResumeAfter()` to resume the change stream. If the token references an oplog position that no longer exists, MongoDB returns `ChangeStreamHistoryLost` (error code 286). The watcher had no code path to handle this — it retried with the same stale token for 60 seconds, fell back from SecondaryPreferred to Primary (which also fails because the token is the problem, not the read preference), and returned a fatal error.

**Evidence from production cluster :**
- fault-remediation resume token timestamp: ~Feb 2, 2026; node-drainer: ~Feb 2, 2026
- Oldest oplog entry: ~Mar 17, 2026 — a **6-week gap** between stored tokens and available oplog
- The 990MB oplog rolled over in ~338 hours (~14 days of retention), confirming even quiet clusters expire old positions
- ~1000 MongoDB error log entries in 23 minutes, all identical `ChangeStreamHistoryLost` retries

fault-quarantine was immune because it watches for health event inserts (broadest filter, most frequent events), so its resume token stays within the oplog window. fault-remediation watches for events where both quarantine AND drain are complete (narrowest filter), so its token ages fastest.

### Root Cause 2: Health Endpoint Not Available During Initialization

Both fault-remediation (`mgr.Start()`) and node-drainer (metrics server) only started their HTTP health endpoints **after** all MongoDB initialization completed. Since initialization was blocked retrying the stale resume token, the health endpoint never opened. The liveness probe (starts at `t=15s`, kills after 3 failures at `~t=55-60s`) got `connection refused` and killed the pod. Each restart loaded the same stale token.

**Evidence from cluster logs and Prometheus:**
- All `Unhealthy` events show `connection refused` — confirming the health port was not listening at all, not an HTTP error
- Startup-to-death deltas match the liveness probe window exactly (~60s per attempt)
- Pod restart counts climbed steadily: fault-remediation `1 → 3 → 5 → 7 → 9` in ~20 minutes; node-drainer `0 → 2 → 4 → 7 → 9` in the same window
- Both modules confirmed in `CrashLoopBackOff` by `kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"}`
- **Zero restarts for fault-quarantine** across the entire window — because FQ serves its health endpoint immediately via concurrent `errgroup` startup

### The Fatal Cycle

```
Pod starts
  → Loads stale resume token from MongoDB
    → openChangeStreamWithRetry retries same bad token for 60s
      → Health endpoint not serving (init not complete)
        → Liveness probe: connection refused at t=15s, t=35s, t=55s
          → failureThreshold=3 reached → SIGTERM → context canceled
            → Kubernetes restarts pod with same stale token
              → CrashLoopBackOff (9+ restarts observed)
```

**Manual fix that broke the cycle:** `db.ResumeTokens.deleteMany({})` + rollout restart — removes the stale token so the next restart opens a fresh change stream. Init completes in seconds, health endpoint starts, liveness passes.

### Fix 1: Stale Resume Token Auto-Recovery

**File:** `store-client/pkg/datastore/providers/mongodb/watcher/watch_store.go`

- Added `isUnrecoverableResumeTokenError()` to detect MongoDB error codes 9 (`FailedToParse`), 260 (`InvalidResumeToken`), 280 (`ChangeStreamFatalError`), and 286 (`ChangeStreamHistoryLost`).
- Added `recoverFromStaleResumeToken()` which deletes the stale token from the `ResumeTokens` collection, clears `ResumeAfter`/`StartAfter` options, and reopens the stream from the current position.
- `openChangeStreamWithRetry()` now detects unrecoverable token errors on the first attempt and triggers recovery immediately instead of retrying for 60 seconds with the same bad token.
- The `Start()` event loop also detects these errors during steady-state operation and deletes the token before exiting, so the next pod restart succeeds immediately.
- Refactored `Start()` into smaller methods (`eventLoop`, `processNextEvent`, `handleChangeStreamError`, `deleteStaleResumeToken`) to satisfy cyclomatic complexity requirements.

### Fix 2: Decouple Health Endpoints From MongoDB Initialization

**File:** `fault-remediation/main.go`

Restructured `setupCtrlRuntimeManagement` to use an `errgroup`. The controller-runtime manager (which serves `/healthz` and `/readyz`) starts in one goroutine while `InitializeAll` + `SetupWithManager` run concurrently in another. Health probes pass immediately during initialization, matching the pattern fault-quarantine already uses. Extracted `createManager()` and `initializeAndWatch()` helpers.

**File:** `node-drainer/main.go`

Moved health/metrics server creation and start above `InitializeAll()` so liveness probes respond during the potentially slow MongoDB setup phase.

### Fix 3: Change Stream Death Detection

A pre-existing gap in all three modules: if the change stream dies during steady-state operation (after initialization succeeds), the pod stays alive but silently stops processing events. fault-quarantine already handled this via its `EventWatcher.Start()` error return. This fix brings fault-remediation and node-drainer to the same standard.

**File:** `fault-remediation/pkg/reconciler/reconciler.go`

`SetupWithManager` now returns a done channel that signals when the event adapter goroutine exits. `initializeAndWatch` monitors this channel — if it closes while the context is still active, the change stream failed unexpectedly and the pod exits so Kubernetes can restart it.

**File:** `node-drainer/main.go`

`startEventWatcher` now sends to the `criticalError` channel when the event channel closes while the context is still active, triggering proper shutdown and restart.

## Test

The E2E Tilt test `TestStaleResumeTokenRecovery` inserts an invalid resume token into MongoDB and restarts fault-remediation. **Without the fix**, the pod enters the retry loop with `(FailedToParse) resume token string was not a valid hex string`, gets killed by the liveness probe, and the stale token remains in the database — the test fails at Step 3 (`the original stale token should have been deleted during recovery`). **With the fix**, `isUnrecoverableResumeTokenError` detects the error on the first attempt, `recoverFromStaleResumeToken` deletes the token and opens a fresh stream, the pod starts successfully, and the test passes with `Resume token after recovery: NOT_FOUND` and pod logs confirming `Resume token is unrecoverable, deleting token and starting fresh`.

## Type of Change
- [x] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 💥 Breaking change
- [ ] 📚 Documentation
- [ ] 🔧 Refactoring
- [ ] 🔨 Build/CI

## Component(s) Affected
- [ ] Core Services
- [ ] Documentation/CI
- [x] Fault Management
- [ ] Health Monitors
- [ ] Janitor
- [ ] Other: ____________

## Testing
- [x] Tests pass locally
- [x] Manual testing completed
- [x] No breaking changes (or documented)

## Checklist
- [x] Self-review completed
- [ ] Documentation updated (if needed)
- [x] Ready for review

## Summary by CodeRabbit

* **New Features**
  * Coordinated, faster service startup and earlier health/metrics availability.
  * Automatic recovery path for stale database resume tokens.

* **Bug Fixes**
  * Improved detection/handling of unexpected change-stream interruptions and safer, timeout-aware shutdown.
  * More accurate recovery when resume-token errors are unrecoverable.

* **Tests**
  * New end-to-end stale-token recovery test and MongoDB test helpers.
  * Additional unit tests covering event adaptation and watcher behavior.

### CODE REVIEW

File: fault-remediation/main.go [hunk 1]
```diff
@@ -105,12 +106,50 @@ func run() error {
...
+		}
+
+		return nil
+	})
+
+	// Initialize datastore and reconciler concurrently — the manager is already
+	// serving health probes, so the pod won't be killed during this phase.
+	g.Go(func() error {
+		return initializeAndWatch(gCtx, params, mgr)
+	})
```
[the remark this answers is not in the document]
Comment (KaivalyaMDabhadkar) [reply fault-remediation/main.go:149]: In this case, fault-remediation is a controller that watches mongodb change streams and creates CRs, it doesn't receive inbound traffic via a service, so there's no consumer that would be affected by premature readiness. The readiness probe's only effect is gating the rolling update termination of the old pod, and early readiness here is acceptable since the pod is healthy (liveness passes) and will begin processing events once init completes.

This is consistent with fault-quarantine's existing pattern, where srv.Serve() (which serves /healthz) starts before mongodb initialization via the same errgroup approach.

File: tests/zz_stale_resume_token_test.go [hunk 2]
```diff
@@ -0,0 +1,292 @@
...
+			return fmt.Errorf("failed to get deployment %s/%s: %w", namespace, name, err)
+		}
+
+		if deployment.Spec.Template.Annotations == nil {
+			deployment.Spec.Template.Annotations = make(map[string]string)
+		}
+		deployment.Spec.Template.Annotations["kubectl.kubernetes.io/restartedAt"] = time.Now().Format(time.RFC3339)
+
+		return client.Resources().Update(ctx, deployment)
+	})
```
[the remark this answers is not in the document]
Comment (KaivalyaMDabhadkar) [reply tests/zz_stale_resume_token_test.go:172]: Addressed

File: fault-remediation/main.go [hunk 3]
```diff
@@ -154,24 +190,28 @@ func setupCtrlRuntimeManagement(ctx context.Context) error {
...
+	case <-ctx.Done():
+		return nil
+	case <-watcherDone:
+		if ctx.Err() == nil {
+			return fmt.Errorf("change stream watcher terminated unexpectedly, event processing has stopped")
+		}
 
-	return nil
+		return nil
+	}
```
[the remark this answers is not in the document]
Comment (KaivalyaMDabhadkar) [reply fault-remediation/main.go]: Addressed

File: tests/zz_stale_resume_token_test.go [hunk 4]
```diff
@@ -0,0 +1,292 @@
...
+
+		// Step 1: Insert a stale resume token
+		t.Log("Step 1: Inserting stale resume token for fault-remediation")
+		helpers.InsertStaleResumeToken(ctx, t, restConfig, mongoPod, "fault-remediation")
+
+		tokenDoc := helpers.GetResumeTokenDoc(ctx, t, restConfig, mongoPod, "fault-remediation")
+		require.NotContains(t, tokenDoc, "NOT_FOUND", "stale token should have been inserted")
+		t.Logf("Stale resume token inserted: %s", tokenDoc)
+
+		// Step 2: Restart fault-remediation — the fix should detect the bad token,
```
Comment (lalitadithya) [inline tests/zz_stale_resume_token_test.go]:
```suggestion
		// Step 2: Restart fault-remediation — should detect the bad token,
```

File: tests/zz_stale_resume_token_test.go [hunk 5]
```diff
@@ -0,0 +1,292 @@
...
+		// The rollout check verifies ALL four replica counters equal the desired
+		// count. With RollingUpdate, a stuck rollout has Replicas=2 (old ready +
+		// new crash-looping) while a completed rollout has Replicas=1. Checking
+		// only ReadyReplicas would false-pass because the OLD pod stays ready.
+		t.Log("Step 2: Restarting fault-remediation (expecting recovery within 2 minutes)")
+		err = triggerDeploymentRestart(ctx, t, client, "fault-remediation", helpers.NVSentinelNamespace)
+		require.NoError(t, err)
+
+		recoveryTimeout := 2 * time.Minute
+		require.Eventually(t, func() bool {
```
Comment (lalitadithya) [inline tests/zz_stale_resume_token_test.go]: can we move this into a helper function if one doesn't already exist?

File: tests/zz_stale_resume_token_test.go [hunk 6]
```diff
@@ -0,0 +1,292 @@
...
+		// After recovery the module should have deleted the bad token and
+		// saved a fresh one (or no token if no events were processed yet).
+		t.Log("Step 3: Verifying stale token was cleaned up")
+		tokenDoc = helpers.GetResumeTokenDoc(ctx, t, restConfig, mongoPod, "fault-remediation")
+		assert.NotContains(t, tokenDoc,
+			helpers.StaleTokenMarker,
+			"the original stale token should have been deleted during recovery")
+		t.Logf("Resume token after recovery: %s", tokenDoc)
+
+		// Step 4: Verify the pod logs confirm the recovery path was taken.
```
Comment (lalitadithya) [inline tests/zz_stale_resume_token_test.go]: Do we need to check logs, can we instead do a remediation flow to confirm?

Checking logs tends to be very flaky

Comment (KaivalyaMDabhadkar) [reply tests/zz_stale_resume_token_test.go]: I think triggering the entire remediation workflow will be a bit overkill for this case. We only want to test that the FR initialized successfully despite an invalid token (or failed initialization in case of some regression).
Regarding flakiness, the log check in Step 4 is intentionally non-fatal to the test (it uses t.Logf rather than require/assert). It's just additional debug evidence, not a hard check. The actual test assertions are in Step 2 (rollout must complete within 2 minutes which proves the pod didn't crash loop) and Step 3 (stale token must be deleted from mongo which proves the recovery path ran)

File: tests/zz_stale_resume_token_test.go (hunk 4 above)
Comment (KaivalyaMDabhadkar) [reply tests/zz_stale_resume_token_test.go]: Addressed

File: tests/zz_stale_resume_token_test.go (hunk 5 above)
Comment (KaivalyaMDabhadkar) [reply tests/zz_stale_resume_token_test.go]: Addressed

File: tests/zz_stale_resume_token_test.go (hunk 6 above)
Comment (KaivalyaMDabhadkar) [reply tests/zz_stale_resume_token_test.go]: Removed the log check as discussed on the call

**Review by lalitadithya — APPROVED** [review]
