### PR TITLE
fix: Add concurrency in event exporter

### LINKED ISSUE #895: [Bug]: ChangeStreamHistoryLost due to sequential publishing throughput bottleneck on large clusters
### Prerequisites

- [x] I searched existing issues
- [x] I can reproduce this issue

### Bug Description

The event-exporter has been non-functional for 4+ days on a 1100+ node cluster, stuck in an infinite error loop logging ChangeStreamHistoryLost without any recovery. All health events from the cluster have gone unexported since Feb 19.

RC: the event-exporter processes and publishes events sequentially at ~3 events/sec, while the cluster produces ~3 events/sec average and ~5 events/sec peak (~11,000 events/hour). The exporter cannot keep up, accumulates backlog, and eventually the MongoDB oplog rotates past its resume token position.

### Evidence 
Event rate from MongoDB (HealthEvents collection, last 24 hours):

- Average: ~11,000 events/hour (~3 events/sec)
- Peak: ~18,000 events/hour (~5 events/sec)
- Sustained 24/7

Event-exporter publish throughput (from Prometheus metrics):
- Average publish duration (p99): ~322ms per event
- Sequential processing: max ~3.1 events/sec (publish only), ~2-2.5 events/sec effective (including decode, transform, MarkProcessed overhead)

At 2-2.5 events/sec effective vs 3 events/sec incoming, the exporter falls behind by ~1,800-3,600 events per hour with no recovery window

### Component

Core Service

### Steps to Reproduce

Flood the event exporter change stream with a slow HTTP remote sink

### Environment

- NVSentinel version: v0.9.0
- Kubernetes version: 1.32
- Deployment method:

### Logs/Output

```
2026-02-19 11:24:44.185 INFO  "Attempting to store resume token" client=event-exporter
2026-02-19 11:24:44.193 ERROR "Failed to watch change stream" error="(ChangeStreamHistoryLost) Resume of change stream was not possible, as the resume point may no longer be in the oplog."
```

### PR DESCRIPTION
**Pull request by XRFXLP**
## Summary

As described in the [linked issue](https://github.com/NVIDIA/NVSentinel/issues/895), event-exporter was failing to keep up with the event production rate on a large cluster (~1100 nodes). The cluster produces ~3 events/sec average (~5 events/sec peak), but the exporter publishes events sequentially at ~2.5 events/sec effective throughput (300ms HTTP POST + resume token write + overhead). This throughput gap caused the exporter to fall progressively behind. Over time, the MongoDB oplog — a fixed-size capped collection — rotated past the exporter's resume token position. On the next reconnection, the exporter hit ChangeStreamHistoryLost and entered an unrecoverable infinite retry loop, leaving all health events unexported for 4+ days.

## Reproduction Strategy

Since the original issue occurred on a production cluster over ~20 hours with a remote sink round-trip of ~300ms, we created a simulated environment to trigger the same failure in minutes:

1. Added a configurable `RESPONSE_DELAY` (300ms) to the mock sink to simulate real-world publish latency
2. Reduced the MongoDB oplog to its minimum size of 990 MB to accelerate rotation
3. Added ~100 KB padding per health event to fill the oplog faster

With these settings, 12,500 events were injected over ~531 seconds in a Kind cluster, generating ~1.25 GB of oplog churn — enough to rotate the 990 MB oplog while the exporter was processing at ~3 events/sec. After restarting the exporter, `ChangeStreamHistoryLost` was reproduced consistently. During active streaming, `CappedPositionLost` was also observed.

## Solution 

There is very little room to optimize the per-event publish latency since it is dominated by network round-trip to the sink. Instead, this MR adds a` --workers` flag to publish events concurrently via a worker pool.

The key challenge with concurrent publishing is resume token ordering: if worker 3 finishes before worker 1, we cannot advance the resume token to worker 3's position — doing so would lose worker 1's event on crash. To solve this, each event is assigned a monotonic sequence number, and a sequence tracker advances the resume token only when all prior events are confirmed delivered (contiguous completion). This guarantees at-least-once delivery with no event loss.

## Verification 

The same simulated environment and test parameters were used with `--workers=10`. The exporter kept up with the event rate (~33 events/sec throughput vs 25 events/sec injection), and no `ChangeStreamHistoryLost` or `CappedPositionLost` errors occurred after restart.

## Scale-up guide 

**Event production rate**: ~10 events/sec per 1000 nodes (11,000 events/hour from 1100 nodes)
**Per-worker throughput**: ~3.3 events/sec (at 300ms publish latency)

| Workers | Throughput (events/sec) | Max Nodes Supported |
|---------|------------------------|--------------------|
| 1       | 3.3                    | ~330               |
| 2       | 6.6                    | ~660               |
| 3       | 9.9                    | ~990               |
| 5       | 16.5                   | ~1,650             |
| 10      | 33                     | ~3,300             | 
| 15      | 49.5                   | ~5,000             |
| 20      | 66                     | ~6,600             |

## Type of Change
- [x] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 💥 Breaking change
- [ ] 📚 Documentation
- [ ] 🔧 Refactoring
- [ ] 🔨 Build/CI

## Component(s) Affected
- [x] Core Services
- [ ] Documentation/CI
- [ ] Fault Management
- [ ] Health Monitors
- [ ] Janitor
- [ ] Other: ____________

## Testing
- [x] Tests pass locally
- [ ] Manual testing completed
- [ ] No breaking changes (or documented)

## Checklist
- [x] Self-review completed
- [ ] Documentation updated (if needed)
- [ ] Ready for review

## Summary by CodeRabbit

* **New Features**
  * Configurable worker count for concurrent event publishing (default: 10).

* **Improvements**
  * Buffered sequence tracking preserves ordered resume-token advancement during parallel publishing.
  * HTTP connection pooling tuned to scale with worker concurrency.
  * Startup logging reports the configured worker count.

* **Tests**
  * Added unit and integration tests for sequence tracking, worker-pool concurrency, ordering, and error handling.

* **Documentation**
  * Docs updated with worker config, scale-up guidance, and examples.

### CODE REVIEW

File: event-exporter/pkg/exporter/worker_pool.go [hunk 1]
```diff
@@ -0,0 +1,170 @@
...
+		}(i)
+	}
+
+	// Close resultCh after all workers finish so tokenWriter exits its range loop
+	go func() {
+		workersWg.Wait()
+		close(wp.resultCh)
+	}()
+
+	return wp.tokenWriter(ctx)
```
[the remark this answers is not in the document]
Comment (XRFXLP) [reply event-exporter/pkg/exporter/worker_pool.go]: We already have this check in upper functions:
```
func (e *HealthEventsExporter) streamEvents(ctx context.Context) error {
	numWorkers := e.workers
	if numWorkers <= 0 {
		numWorkers = 1
	}

	slog.Info("Starting event stream", "workers", numWorkers)

	if numWorkers == 1 {
		return e.streamEventsSequential(ctx)
	}

	return e.streamEventsConcurrent(ctx, numWorkers)
}
```

File: event-exporter/pkg/exporter/exporter.go [hunk 2]
```diff
@@ -284,6 +291,103 @@ func (e *HealthEventsExporter) processEvent(ctx context.Context, healthEvent cli
...
+			}
+
+			*seq++
+
+			if !pool.dispatch(ctx, workItem{
+				seq:         *seq,
+				event:       event,
+				resumeToken: healthEvent.GetResumeToken(),
+			}) {
+				return ctx.Err()
```
[the remark this answers is not in the document]
Comment (XRFXLP) [reply event-exporter/pkg/exporter/exporter.go]: *seq++ is parsed as (*seq)++, not *(seq++)

File: event-exporter/pkg/exporter/exporter.go [hunk 3]
```diff
@@ -229,8 +232,22 @@ func (e *HealthEventsExporter) waitForRateLimit(
...
-	slog.Info("Starting event stream")
+	numWorkers := e.workers
+	if numWorkers <= 0 {
+		numWorkers = 1
+	}
+
+	slog.Info("Starting event stream", "workers", numWorkers)
+
+	if numWorkers == 1 {
+		return e.streamEventsSequential(ctx)
```
Comment (lalitadithya) [inline event-exporter/pkg/exporter/exporter.go]: Isn't `streamEventsSequential` the same as `streamEventsConcurrent` with a single worker do we need 2 different code paths?

File: event-exporter/pkg/exporter/exporter.go [hunk 4]
```diff
@@ -284,6 +291,103 @@ func (e *HealthEventsExporter) processEvent(ctx context.Context, healthEvent cli
...
+
+		case healthEvent, ok := <-e.source.Events():
+			if !ok {
+				slog.Info("Event channel closed, finishing in-flight events")
+				return nil
+			}
+
+			metrics.EventsReceived.Inc()
+
+			event, err := unmarshalHealthEvent(healthEvent)
```
Comment (lalitadithya) [inline event-exporter/pkg/exporter/exporter.go]: instead of error checking here, can we dispatch all of these so the implementation detail of update resume token or publish is contained in the same module.

File: event-exporter/pkg/exporter/exporter.go [hunk 5]
```diff
@@ -284,6 +291,103 @@ func (e *HealthEventsExporter) processEvent(ctx context.Context, healthEvent cli
...
+
+	pool.closeDispatch()
+
+	// Wait for the pool to finish processing in-flight items
+	poolErr := <-poolErrCh
+
+	// When the pool triggers cancellation (e.g., publish failure), consumeErr
+	// is just context.Canceled — prefer poolErr which has the root cause.
+	if poolErr != nil {
+		return poolErr
```
Comment (lalitadithya) [inline event-exporter/pkg/exporter/exporter.go]: can we wrap these errors?

Comment (XRFXLP) [reply event-exporter/pkg/exporter/exporter.go]: Done

File: event-exporter/pkg/exporter/exporter.go (hunk 4 above)
Comment (XRFXLP) [reply event-exporter/pkg/exporter/exporter.go]: Done

File: event-exporter/pkg/exporter/exporter.go (hunk 3 above)
Comment (XRFXLP) [reply event-exporter/pkg/exporter/exporter.go]: Should be handled now

**Review by lalitadithya — APPROVED** [review]
