### PR TITLE
fix: Clean up nolint directives marked as TODO - Part 2

### LINKED ISSUE #728: [Code Quality]: Clean up `nolint` directives marked as TODO and add missing justifications
### Prerequisites

- [x] I searched existing issues

### Maintainence request

Linter directives (`nolint`) should either be:
1. Properly justified with a clear reason why the lint rule cannot be satisfied
2. Removed by refactoring the code to satisfy the linter

Currently we've have 100+ fixable nolint directives across the repo that were probably added when we enabled global linter.

### PR DESCRIPTION
**Pull request by cbumb**
## Summary

Refactors nolint directives by lowering complexity and improving structure. No intended behavior change.
Modules updated in this PR:
- health-monitors

## Type of Change
- [ ] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 💥 Breaking change
- [ ] 📚 Documentation
- [x] 🔧 Refactoring
- [ ] 🔨 Build/CI

## Component(s) Affected
- [x] Core Services
- [ ] Documentation/CI
- [ ] Fault Management
- [x] Health Monitors
- [ ] Janitor
- [ ] Other: ____________

## Testing
- [x] Tests pass locally
- [x] Manual testing completed
- [x] No breaking changes (or documented)

## Checklist
- [x] Self-review completed
- [x] Documentation updated (if needed)
- [x] Ready for review

## Release Notes

* **New Features**
  * Added boot detection to automatically reset health state after system reboot
  * Implemented exponential backoff for periodic health checks (capped at 30 seconds)
  * Added unit-level filtering support for syslog entries

* **Bug Fixes**
  * Improved error handling and recovery paths in journal processing
  * Enhanced resilience with retry logic for transient failures
  * Better state persistence and end-of-journal handling

### CODE REVIEW

File: health-monitors/csp-health-monitor/pkg/csp/gcp/gcp.go [hunk 1]
```diff
@@ -393,20 +393,23 @@ func (c *Client) getNodeNameForGcpLogEntry(
...
 
 		nodeName, mappingErr = c.mapGCPInstanceToNodeName(ctx, gcpNumericInstanceID, eventMetaForMapper)
-		//nolint:gocritic
 		if mappingErr != nil {
 			slog.Warn("Error mapping GCP resource ID to K8s node name. Proceeding without node name",
 				"instanceID", gcpNumericInstanceID,
 				"zone", gcpZone,
 				"error", mappingErr)
-		} else if nodeName == "" {
+		}
```
Comment (XRFXLP) [inline health-monitors/csp-health-monitor/pkg/csp/gcp/gcp.go:403]: should we just return here and eliminate `if mapingErr == nil` checks below?

File: health-monitors/csp-health-monitor/pkg/event/processor.go
Comment (XRFXLP) [inline health-monitors/csp-health-monitor/pkg/event/processor.go]: Looks like we can simplify this by using de morgan's law: should we have a function named `emptyOrDefault`? this would make if first clause as:
```
if emptyOfDefault(event.ResourceID) && !emptyOfDefault(prior.Resource.ID)
```
?
and similarly for function below? Would that bring down complexity?

Comment (XRFXLP) [inline health-monitors/csp-health-monitor/pkg/event/processor.go]: Same comment as above. And also it looks lke we're repeating few of the stuffs in the function above as well

File: health-monitors/syslog-health-monitor/pkg/syslog-monitor/syslogmonitor.go [hunk 2]
```diff
@@ -194,7 +195,7 @@ func saveState(stateFilePath string, state syslogMonitorState) error {
 
 // loadState loads the monitor state from a file
 //
-//nolint:cyclop,gocognit // TODO
+//nolint:cyclop,gocognit // linear load with fallbacks (missing, empty, corrupt, version); refactor would not simplify
```
Comment (XRFXLP) [inline health-monitors/syslog-health-monitor/pkg/syslog-monitor/syslogmonitor.go]: how about something like this:
```
	data, err := readStateFile(stateFilePath)
	if err != nil {
		return syslogMonitorState{}, err
	}

	if data == nil {
		return newDefaultState(), nil
	}

	state, ok := parseStateData(stateFilePath, data)
	if !ok {
		return newDefaultState(), nil
	}

	// Version migration needed if not zero and not current
	if state.Version != 0 && state.Version != stateFileVersion {
		return migrateStateVersion(stateFilePath, state)
	}

	return ensureStateInitialized(state), nil
```

File: health-monitors/syslog-health-monitor/pkg/syslog-monitor/syslogmonitor.go [hunk 3]
```diff
@@ -59,7 +60,7 @@ func NewSyslogMonitor(
 
 // NewSyslogMonitorWithFactory creates a new SyslogMonitor instance with a specific journal factory
 //
-//nolint:cyclop
+//nolint:cyclop // constructor + switch over check types; refactor would not simplify
```
Comment (XRFXLP) [inline health-monitors/syslog-health-monitor/pkg/syslog-monitor/syslogmonitor.go]: Can we create a another function for initializing handlers and use it here? would that help in getting rid of cyclop?

File: health-monitors/syslog-health-monitor/pkg/syslog-monitor/syslogmonitor.go [hunk 4]
```diff
@@ -507,7 +541,7 @@ func (sm *SyslogMonitor) configureTagFilters(journal Journal, check CheckDefinit
 
 // processJournalEntries reads and processes journal entries
 //
-//nolint:gocognit,cyclop
+//nolint:gocognit,cyclop // single flow: init or resume, then process loop with recovery; splitting would scatter logic
```
Comment (XRFXLP) [inline health-monitors/syslog-health-monitor/pkg/syslog-monitor/syslogmonitor.go]: this function has mainly three subsections:
1. Initialize from journal tail (you've already created function for this)
2. Otherwise resume from last cursor 
3. Process all entries

should we create the last two function?

**Review by XRFXLP — APPROVED** [review]
