### PR TITLE
fix: Clean up nolint directives marked as TODO - Part 3

### LINKED ISSUE #728: [Code Quality]: Clean up `nolint` directives marked as TODO and add missing justifications
### Prerequisites

- [x] I searched existing issues

### Maintainence request

Linter directives (`nolint`) should either be:
1. Properly justified with a clear reason why the lint rule cannot be satisfied
2. Removed by refactoring the code to satisfy the linter

Currently we've have 100+ fixable nolint directives across the repo that were probably added when we enabled global linter.

### PR DESCRIPTION
**Pull request by cbumb**
## Summary
Refactors nolint directives by lowering complexity and improving structure. No intended behavior change.
Modules updated in this PR:

janitor

## Type of Change
- [ ] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 💥 Breaking change
- [ ] 📚 Documentation
- [x] 🔧 Refactoring
- [ ] 🔨 Build/CI

## Component(s) Affected
- [x] Core Services
- [ ] Documentation/CI
- [ ] Fault Management
- [x] Health Monitors
- [ ] Janitor
- [ ] Other: ____________

## Testing
- [x] Tests pass locally
- [x] Manual testing completed
- [x] No breaking changes (or documented)

## Checklist
- [x] Self-review completed
- [x] Documentation updated (if needed)
- [x] Ready for review

## Summary by CodeRabbit

* **Refactor**
  * Startup, CLI and server wiring reorganized into modular initialization for clearer startup flow.

* **Style**
  * Localized lint annotations and tightened inline formatting to improve readability.

* **Bug Fixes**
  * Config loading reliably falls back to built-in defaults when no config file is present.

* **Behavior**
  * Default settings now propagate to additional node operations; controllers requeue on transient CSP/gRPC errors with backoff.

* **Documentation**
  * Shortened column descriptions for target node and status.

* **Tests**
  * Added coverage for transient CSP/gRPC error handling.

### CODE REVIEW

File: janitor/main.go [hunk 1]
```diff
@@ -62,6 +62,30 @@ func init() {
...
+	secureMetrics                                    bool
+	enableHTTP2                                      bool
+	configFile                                       string
+	leaseDuration                                    time.Duration
+	renewDeadline                                    time.Duration
+	retryPeriod                                      time.Duration
+}
+
+// tlsAndServers holds the webhook server, metrics options, and optional cert watchers.
+type tlsAndServers struct {
```
Comment (XRFXLP) [inline janitor/main.go]: Should we split this into multiple structure? `serverConfig` and `certWatchers`? Or if we're keeping one then use a better name?

Comment (cbumb) [reply janitor/main.go]: IMO having a single structure is convenient. I will rename it to `serverSetup`

File: janitor/pkg/controller/rebootnode_controller.go [hunk 2]
```diff
@@ -98,222 +107,319 @@ func (r *RebootNodeReconciler) Reconcile(ctx context.Context, req ctrl.Request)
...
+	slog.Info("Sending reboot signal to node", "node", node.Name)
+
+	rsp, rebootErr := r.CSPClient.SendRebootSignal(ctx, &cspv1alpha1.SendRebootSignalRequest{
+		NodeName: node.Name,
+	})
+
+	var condition metav1.Condition
+
+	if rebootErr == nil {
+		metrics.GlobalMetrics.IncActionCount(metrics.ActionTypeReboot, metrics.StatusStarted, node.Name)
```
Comment (XRFXLP) [inline janitor/pkg/controller/rebootnode_controller.go]: Earlier we were sending this metric irrespective of `rebootErr`. Can we have the same behaviour?

File: janitor/pkg/controller/rebootnode_controller.go [hunk 3]
```diff
@@ -98,222 +107,319 @@ func (r *RebootNodeReconciler) Reconcile(ctx context.Context, req ctrl.Request)
...
-			})
-			if nodeReadyErr != nil {
-				cspReady = false
-			} else {
-				cspReady = rsp.IsReady
+		result = r.handleRebootInProgress(ctx, rebootNode, &node)
+	} else {
+		var err error
+
+		result, err, statusPersisted = r.handleRebootNotStarted(ctx, originalRebootNode, rebootNode, &node)
```
Comment (XRFXLP) [inline janitor/pkg/controller/rebootnode_controller.go]: Can we have same signature here as above `handleRebootInProgress`? Also why can't we have just simply:
```go
	if rebootNode.IsRebootInProgress() {
		result = r.handleRebootInProgress(ctx, rebootNode, &node)
	} else {
		result = r.handleRebootNotStarted(ctx, rebootNode, &node)
	}

	if err := r.updateRebootNodeStatusIfChanged(ctx, originalRebootNode, rebootNode); err != nil {
		if errors.Is(err, errRebootNodeDeleted) {
			return ctrl.Result{}, nil
		}

		return ctrl.Result{}, err
	}
```


It looks we're double calling `updateRebootNodeStatusIfChanged` inside `handleRebootNotStarted` even though it is already called in `reconcileHelper`

**Review by XRFXLP — APPROVED** [review]
