### PR TITLE
fix: Clean up nolint directives marked as TODO - Part 5

### LINKED ISSUE #728: [Code Quality]: Clean up `nolint` directives marked as TODO and add missing justifications
### Prerequisites

- [x] I searched existing issues

### Maintainence request

Linter directives (`nolint`) should either be:
1. Properly justified with a clear reason why the lint rule cannot be satisfied
2. Removed by refactoring the code to satisfy the linter

Currently we've have 100+ fixable nolint directives across the repo that were probably added when we enabled global linter.

### PR DESCRIPTION
**Pull request by cbumb**
## Summary
Refactors nolint directives by lowering complexity and improving structure. No intended behavior change.

Modules updated in this PR:
store-client

## Type of Change
- [ ] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 💥 Breaking change
- [ ] 📚 Documentation
- [x] 🔧 Refactoring
- [ ] 🔨 Build/CI

## Component(s) Affected
- [x] Core Services
- [ ] Documentation/CI
- [ ] Fault Management
- [ ] Health Monitors
- [ ] Janitor
- [ ] Other: ____________

## Testing
- [x] Tests pass locally
- [x] Manual testing completed
- [x] No breaking changes (or documented)

## Checklist
- [x] Self-review completed
- [x] Documentation updated (if needed)
- [x] Ready for review

## Summary by CodeRabbit

* **New Features**
  * Added PostgreSQL helpers for easier database client access and streamlined change-stream watcher creation.
  * Exposed a helper to obtain a configured MongoDB collection client.

* **Bug Fixes**
  * More reliable resume-positioning and inner-document extraction for change streams.
  * Improved value comparisons and operator handling to reduce filtering errors.
  * Fixed SQL parameter ordering for update-by-query paths.

* **Refactor**
  * Consolidated parsing and processing into reusable helpers and replaced literal operators with constants.

* **Breaking Change**
  * Removed one MongoDBConfig field (UnprocessedEventsMetricUpdateIntervalSeconds).

* **Tests**
  * Added unit coverage for pointer-copy behavior in struct copying.

### CODE REVIEW

File: store-client/pkg/storewatcher/watch_store.go [hunk 1]
```diff
@@ -444,34 +462,22 @@ func GetCollectionClient(
...
-
-	if mongoConfig.TotalPingIntervalSeconds <= 0 {
-		return nil, fmt.Errorf("invalid ping interval value, value must be a positive integer")
-	}
-
-	if mongoConfig.TotalPingIntervalSeconds >= mongoConfig.TotalPingTimeoutSeconds {
-		return nil, fmt.Errorf("invalid ping interval value, value must be less than ping timeout")
+	totalTimeout, interval, err := validatePingConfig(mongoConfig)
+	if err != nil {
+		return nil, err
```
Comment (XRFXLP) [inline store-client/pkg/storewatcher/watch_store.go]: nit: Can we wrap the error here and the earlier call? I know we've error wrapping present in the validatePingConfig but adding wrapper in caller function would help in disambiguating on which call is failing (if any)

**Review by KaivalyaMDabhadkar — APPROVED** [review]
