### PR TITLE
fix: Clean up nolint directives marked as TODO - Part 1

### LINKED ISSUE #728: [Code Quality]: Clean up `nolint` directives marked as TODO and add missing justifications
### Prerequisites

- [x] I searched existing issues

### Maintainence request

Linter directives (`nolint`) should either be:
1. Properly justified with a clear reason why the lint rule cannot be satisfied
2. Removed by refactoring the code to satisfy the linter

Currently we've have 100+ fixable nolint directives across the repo that were probably added when we enabled global linter.

### PR DESCRIPTION
**Pull request by cbumb**
## Summary

Refactors fault-remediation config validation and initializer to remove `nolint` directives by lowering complexity and improving structure. No intended behavior change.
Modules updated in this PR:
- fault-quarantine
- fault-remediation

## Type of Change
- [ ] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 💥 Breaking change
- [ ] 📚 Documentation
- [x] 🔧 Refactoring
- [ ] 🔨 Build/CI

## Component(s) Affected
- [x] Core Services
- [ ] Documentation/CI
- [ ] Fault Management
- [x] Health Monitors
- [ ] Janitor
- [ ] Other: ____________

## Testing
- [x] Tests pass locally
- [x] Manual testing completed
- [x] No breaking changes (or documented)

## Checklist
- [x] Self-review completed
- [x] Documentation updated (if needed)
- [x] Ready for review

## Summary by CodeRabbit

* **New Features**
  * Gang coordination for init containers (discovery, coordination, and registration) and a new GPU reset remediation action.
  * Action-driven remediation templates enabling per-action CR creation.

* **Bug Fixes**
  * Stronger maintenance config validation with clearer, action-scoped error messages; rejects invalid or self-referencing superseding groups and empty template mounts.
  * More consistent remediation status/annotation handling.

* **Improvements**
  * More robust startup/initialization, log-collector orchestration, and retry/backoff behaviors; improved observability.

* **Tests / Docs**
  * Expanded tests, new scale-test manifests/results and updated docs/examples for maintenance and mixed-eviction scenarios.

### CODE REVIEW

File: fault-remediation/pkg/initializer/init.go [hunk 1]
```diff
@@ -48,32 +48,21 @@ type Components struct {
...
 	params InitializationParams,
 	ctrlruntimeClient ctrlruntimeClient.Client,
 ) (*Components, error) {
 	slog.Info("Starting fault remediation module initialization")
 
-	tokenConfig, err := storeconfig.TokenConfigFromEnv("fault-remediation")
+	tokenConfig, tomlConfig, err := loadTokenAndTomlConfig(params)
 	if err != nil {
-		return nil, fmt.Errorf("failed to load token configuration: %w", err)
+		return nil, err
```
Comment (lalitadithya) [inline fault-remediation/pkg/initializer/init.go:60]: Please don't remove error wrapping, we always wrap errors with additional context

Comment (cbumb) [reply fault-remediation/pkg/initializer/init.go:60]: The error already has context from loadTokenAndTomlConfig() (it wraps with fmt.Errorf there). We’re just returning that wrapped error, so no context is lost.

**Review by KaivalyaMDabhadkar — DISMISSED** [review]

**Review by KaivalyaMDabhadkar — APPROVED** [review]
