### PR TITLE
fix: add pre-installed driver support in labeler module

### LINKED ISSUE #348: [Bug]: XID detection is not working when nodes have pre-installed drivers
### Prerequisites

- [x] I searched existing issues
- [x] I can reproduce this issue

### Bug Description

In some environments, the driver is managed directly on the node using a machine image. In such environments, GPU operator is configured to not install the driver, but just install the toolkit, device plugin and DCGM. In such environments the XID detection is not working as syslog health monitor is not deployed

### Component

Health Monitor

### Steps to Reproduce

1. Bring up a GKE cluster with driver pre-installed
2. Deploy NVSentinel
3. Inject XID to syslogs
4. Notice that node is never cordoned << expected node to be coroned

### Environment

- NVSentinel version: 0.3.0
- Kubernetes version: 1.33
- Deployment method: Helm

### Logs/Output

I noticed that label `driver.installed` is missing from the nodes due to a lack of the driver pods which is likely what is causing the issue.

### LINKED ISSUE #349: [Bug]: XID detection is not working on environments with GKE COS
### Prerequisites

- [x] I searched existing issues
- [x] I can reproduce this issue

### Bug Description

In GKE, it is possible to make use of the google driver installer to install the driver as it is documented in https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/google-gke.html#using-the-google-driver-installer and in such cases the syslog health monitor is not deployed and hence it is missing XID detection

### Component

Health Monitor

### Steps to Reproduce

1. Bring up a GKE cluster with COS and google driver installer
2. Deploy NVSentinel
3. Inject XID to syslogs
4. Notice that node is never cordoned << expected node to be coroned

### Environment

- NVSentinel version: 0.3.0
- Kubernetes version: 1.33
- Deployment method: Helm

### Logs/Output

I noticed that label `driver.installed` is missing from the nodes due to a lack of the driver pods which is likely what is causing the issue.

### PR DESCRIPTION
**Pull request by tanishagoyal2**
## Type of Change
- [x] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 💥 Breaking change
- [ ] 📚 Documentation
- [ ] 🔧 Refactoring
- [ ] 🔨 Build/CI

## Component(s) Affected
- [ ] Core Services
- [ ] Documentation/CI
- [ ] Fault Management
- [ ] Health Monitors
- [ ] Janitor
- [x] Other: ____________

## Testing
- [x] Tests pass locally
- [x] Manual testing completed
- [x] No breaking changes (or documented)

## Checklist
- [x] Self-review completed
- [x] Documentation updated (if needed)
- [x] Ready for review

Context: https://github.com/NVIDIA/NVSentinel/blob/main/docs/designs/018-syslog-monitor-preinstalled-driver-support.md

### Testing
1. I have updated unit test
2. I have tested these changes in runai GCP cluster where nvidia-driver-daemonset is not preset so GPU nodes were not labled by labeler
After applying new labeler image with changes, the labeler applied driver.installed label to all GPU nodes

Screenshot 2025-12-03 at 3 37 00 PM

I have also confirmed that labels were only added to GPU nodes. CPU nodes didn't have this label.

3. Tested on non-GCP cluster. Labeler applied labels only on GPU node.
    a. First I removed the applied labels on GPU node
    b. restarted the labeler pod with new image
    c. observed GPU node had nvsentinel.dgxc.nvidia.com/driver.installed=true label

Screenshot 2025-12-04 at 10 21 00 AM

## Summary by CodeRabbit

* **New Features**
  * Detects GKE driver installer pods so nodes with GKE-installed drivers are labeled correctly.

* **Documentation**
  * Expanded "Driver Installed" docs to explain detection methods, GKE-specific notes for pre-installed drivers, and a manual labeling example.

* **Tests**
  * Updated tests to cover installer-based driver detection and label behavior across installer pod lifecycle events.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: labeler/pkg/labeler/labeler.go [hunk 1]
```diff
@@ -126,15 +142,39 @@ func NewLabeler(clientset kubernetes.Interface, resyncPeriod time.Duration,
...
-		kataLabels:      kataLabels,
+		clientset:            clientset,
+		podInformer:          podInformer,
+		nodeInformer:         nodeInformer,
+		gkeInstallerInformer: gkeInstallerInformer,
+		informersSynced: []cache.InformerSynced{
+			podInformer.HasSynced,
+			nodeInformer.HasSynced,
+			gkeInstallerInformer.HasSynced},
+		ctx:                  context.Background(),
```
Comment (lalitadithya) [inline labeler/pkg/labeler/labeler.go]:
```suggestion
			gkeInstallerInformer.HasSynced
		},
		ctx:                  context.Background(),
```

File: labeler/pkg/labeler/labeler.go [hunk 2]
```diff
@@ -279,24 +341,48 @@ func (l *Labeler) getDCGMVersionForNode(nodeName string) (string, error) {
...
 		}
 
+		// Skip the pod we're excluding (used for delete events)
+		if excludePod != nil && pod.UID == excludePod.UID {
+			continue
+		}
+
 		if podutil.IsPodReady(pod) {
-			return LabelValueTrue, nil
+			return true
```
Comment (lalitadithya) [inline labeler/pkg/labeler/labeler.go:359]: Can we continue to use `LabelValueTrue`?

Comment (tanishagoyal2) [reply labeler/pkg/labeler/labeler.go:359]: This function is to check if there is any driver pod ready on the node or not. 
If you check line 374, if there is driver pod in ready state then its returning `LabelValueTrue` only.

File: labeler/pkg/labeler/labeler.go (hunk 1 above)
Comment (tanishagoyal2) [reply labeler/pkg/labeler/labeler.go]: updated

File: labeler/pkg/labeler/labeler_test.go [hunk 3]
```diff
@@ -154,6 +154,39 @@ func TestLabeler_handlePodEvent(t *testing.T) {
...
+			existingPods: []*corev1.Pod{},
+			existingNode: &corev1.Node{
+				ObjectMeta: metav1.ObjectMeta{
+					Name:   "test-node",
+					Labels: map[string]string{},
+				},
+			},
+			expectedDCGMLabel:   "",
+			expectedDriverLabel: "true",
+		},
```
[the remark this answers is not in the document]
Comment (tanishagoyal2) [reply labeler/pkg/labeler/labeler_test.go:189]: updated, check now

**Review by lalitadithya — APPROVED** [review]
