### PR TITLE
fix: Clean up nolint directives marked as TODO - Part 4

### LINKED ISSUE #728: [Code Quality]: Clean up `nolint` directives marked as TODO and add missing justifications
### Prerequisites

- [x] I searched existing issues

### Maintainence request

Linter directives (`nolint`) should either be:
1. Properly justified with a clear reason why the lint rule cannot be satisfied
2. Removed by refactoring the code to satisfy the linter

Currently we've have 100+ fixable nolint directives across the repo that were probably added when we enabled global linter.

### PR DESCRIPTION
**Pull request by cbumb**
## Summary

Refactors nolint directives by lowering complexity and improving structure. No intended behavior change.

Modules updated in this PR:
- labeler
- metadata-collector
- node-drainer
- platform-connectors
- preflight-checks
- tests

## Type of Change
- [ ] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 💥 Breaking change
- [ ] 📚 Documentation
- [x] 🔧 Refactoring
- [ ] 🔨 Build/CI

## Component(s) Affected
- [x] Core Services
- [ ] Documentation/CI
- [ ] Fault Management
- [ ] Health Monitors
- [ ] Janitor
- [ ] Other: ____________

## Testing
- [x] Tests pass locally
- [x] Manual testing completed
- [x] No breaking changes (or documented)

## Checklist
- [x] Self-review completed
- [x] Documentation updated (if needed)
- [x] Ready for review

## Summary by CodeRabbit

* **Bug Fixes**
  * Enforced TLS1.2 for kubelet connections; improved HTTP response/resource handling and richer error messages.

* **New Features**
  * Added public initialization parameters and a Components result to simplify configurable startup.

* **Improvements**
  * Modularized informer/indexing setup; batched per-node condition processing with safer timestamps and aggregated messages; clearer drain/quarantine and cancellation handling; safer init teardown on failure.

* **Tests**
  * Added extensive label-watcher tests, kata-label and reconciler test additions; updated connector and node-condition tests.

### CODE REVIEW

File: node-drainer/pkg/reconciler/reconciler.go [hunk 1]
```diff
@@ -635,7 +640,6 @@ func (r *Reconciler) HandleCancellation(eventID string, nodeName string, status
 
 	slog.Debug("HandleCancellation called", "node", nodeName, "eventID", eventID, "status", status)
 
-	//nolint:exhaustive // we don't need to handle other statuses
```
Comment (cbumb) [inline node-drainer/pkg/reconciler/reconciler.go:654]: Should we keep this nolint as is or adding the changes on line#664 valid?
I was thinking to keep the nolint incase we miss any status

File: preflight-checks/nccl-loopback/pkg/benchmark/benchmark.go [hunk 2]
```diff
@@ -49,9 +50,14 @@ type Runner struct {
 	binaryPath string
 }
 
-// NewRunner creates a new benchmark runner.
-func NewRunner(binaryPath string) *Runner {
-	return &Runner{binaryPath: binaryPath}
+// NewRunner creates a new benchmark runner. Returns an error if binaryPath is empty or invalid.
+func NewRunner(binaryPath string) (*Runner, error) {
+	cleaned := filepath.Clean(binaryPath)
```
Comment (XRFXLP) [inline preflight-checks/nccl-loopback/pkg/benchmark/benchmark.go]: `NewRunner` is initialized after config validation in `config.FromEnv`, which calls the following function:
```go
func parseBinaryPath() (string, error) {
	path := os.Getenv("NCCL_TEST_BINARY_PATH")
	if path == "" {
		path = "/opt/nccl-tests/build/all_reduce_perf"
	}

	if err := validateExecutable(path); err != nil {
		slog.Error("Binary validation failed", "path", path, "error", err)
		return "", fmt.Errorf("invalid NCCL_TEST_BINARY_PATH: %w", err)
	}

	slog.Debug("Binary validated successfully", "path", path)

	return path, nil
}
```

Where we already do the validation, why do we need this change?

Comment (cbumb) [reply preflight-checks/nccl-loopback/pkg/benchmark/benchmark.go]: Makes sense. Resolved

File: node-drainer/pkg/reconciler/reconciler.go (hunk 1 above)
Comment (cbumb) [reply node-drainer/pkg/reconciler/reconciler.go:654]: @XRFXLP thoughts?

File: platform-connectors/pkg/connectors/kubernetes/process_node_events.go [hunk 3]
```diff
@@ -417,6 +430,48 @@ func (r *K8sConnector) processHealthEvents(ctx context.Context, healthEvents *pr
...
+	grouped := make(map[string][]*protos.HealthEvent)
+
+	for _, e := range events {
+		grouped[e.NodeName] = append(grouped[e.NodeName], e)
+	}
+
+	return grouped
+}
+
+func (r *K8sConnector) processNodeConditionUpdates(ctx context.Context, nodeName string,
```
Comment (XRFXLP) [inline platform-connectors/pkg/connectors/kubernetes/process_node_events.go]: `nodeName` name parameter here is unused, can you please check?

File: platform-connectors/pkg/connectors/kubernetes/process_node_events.go [hunk 4]
```diff
@@ -41,12 +43,55 @@ const (
 	truncationSuffix   = "..."
 )
 
-//nolint:cyclop, gocognit
+// updateNodeConditions updates node conditions for a single node.
+// All healthEvents must belong to the same node; callers must partition by NodeName.
 func (r *K8sConnector) updateNodeConditions(ctx context.Context, healthEvents []*protos.HealthEvent) error {
-	sortedHealthEvents := slices.Clone(healthEvents)
+	if len(healthEvents) == 0 {
```
Comment (XRFXLP) [inline platform-connectors/pkg/connectors/kubernetes/process_node_events.go]: Can this be empty?
From the looks of it, the health events are coming from:
```
func groupEventsByNode(events []*protos.HealthEvent) map[string][]*protos.HealthEvent {
	grouped := make(map[string][]*protos.HealthEvent)

	for _, e := range events {
		grouped[e.NodeName] = append(grouped[e.NodeName], e)
	}

	return grouped
}
```

File: node-drainer/pkg/reconciler/reconciler.go (hunk 1 above)
Comment (XRFXLP) [reply node-drainer/pkg/reconciler/reconciler.go:654]: LGTM

File: labeler/pkg/labeler/labeler.go [hunk 5]
```diff
@@ -79,47 +79,75 @@ func (l *Labeler) allInformersSynced() bool {
...
-	if kataLabelOverride != "" {
+	if kataLabelOverride != "" && kataLabelOverride != KataRuntimeDefaultLabel {
 		kataLabels = append(kataLabels, kataLabelOverride)
 	}
 
-	// Create pod informer factory with label selector
+	return kataLabels
+}
+
+func createPodInformer(clientset kubernetes.Interface, resyncPeriod time.Duration,
```
Comment (XRFXLP) [inline labeler/pkg/labeler/labeler.go:129]: It looks we have significant repetitions between `createPodInformer` and `createGKEInstallerInformer`. Can we factor out the skeleton of it and make these functions a thin wrapper over the skeleton?

The end result can look something like:
```go
func createPodInformer(clientset kubernetes.Interface, resyncPeriod time.Duration,
	dcgmApp, driverApp string) (cache.SharedIndexInformer, error) {
	return createIndexedPodInformer(clientset, resyncPeriod,
		fmt.Sprintf("app in (%s,%s)", dcgmApp, driverApp),
		cache.Indexers{
			NodeDCGMIndex:   podNodeIndexerByLabel("app", dcgmApp),
			NodeDriverIndex: podNodeIndexerByLabel("app", driverApp),
		},
	)
}

func createGKEInstallerInformer(clientset kubernetes.Interface, resyncPeriod time.Duration,
	gkeInstallerApp string) (cache.SharedIndexInformer, error) {
	return createIndexedPodInformer(clientset, resyncPeriod,
		fmt.Sprintf("k8s-app=%s", gkeInstallerApp),
		cache.Indexers{
			NodeGKEDriverInstallerIndex: podNodeIndexerByLabel("k8s-app", gkeInstallerApp),
		},
	)
}
```

And in this way, we can add future informers easily as well.

File: labeler/pkg/labeler/labeler.go [hunk 6]
```diff
@@ -79,47 +79,75 @@ func (l *Labeler) allInformersSynced() bool {
...
+		podInformer:          podInformer,
+		nodeInformer:         nodeInformer,
+		gkeInstallerInformer: gkeInstallerInformer,
+		informersSynced: []cache.InformerSynced{
+			podInformer.HasSynced,
+			nodeInformer.HasSynced,
+			gkeInstallerInformer.HasSynced,
+		},
+		ctx:                  context.Background(),
+		dcgmAppLabel:         dcgmApp,
```
Comment (XRFXLP) [inline labeler/pkg/labeler/labeler.go]: Are these labels used anywhere or just being stored? Can we remove them if these fields are not used?

**Review by XRFXLP — APPROVED** [review]
